#!/usr/bin/env sh
set -ex # Stop on first error and log all commands

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -pedantic -std=c89"

# Build solution for each day
$CC $CFLAGS -o 01a 01a.c
$CC $CFLAGS -o 01b 01b.c
