#!/usr/bin/env sh
set -e # Stop on first error

CC="cc"
CFLAGS="-Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -pedantic -std=c99"

mkdir -p bin

# Build all programs
for src in `ls *.c`
do
    out=$( echo $src | sed 's/.c//' )
    $CC $CFLAGS -o bin/$out $src
done
